package catalogo.consultpide.org.buscaruc.buscaruc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-04-21T17:47:41.231-05:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "BuscaRuc",
                  wsdlLocation = "file:/C:/catalogoDigital/consultPide/src/main/resources/ruc.wsdl",
                  targetNamespace = "http://www.BuscaRuc.org/BuscaRuc/")
public class BuscaRuc_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://www.BuscaRuc.org/BuscaRuc/", "BuscaRuc");
    public static final QName BuscaRucSOAP = new QName("http://www.BuscaRuc.org/BuscaRuc/", "BuscaRucSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/catalogoDigital/consultPide/src/main/resources/ruc.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BuscaRuc_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/catalogoDigital/consultPide/src/main/resources/ruc.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BuscaRuc_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BuscaRuc_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BuscaRuc_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BuscaRuc_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BuscaRuc_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BuscaRuc_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BuscaRuc
     */
    @WebEndpoint(name = "BuscaRucSOAP")
    public BuscaRuc getBuscaRucSOAP() {
        return super.getPort(BuscaRucSOAP, BuscaRuc.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BuscaRuc
     */
    @WebEndpoint(name = "BuscaRucSOAP")
    public BuscaRuc getBuscaRucSOAP(WebServiceFeature... features) {
        return super.getPort(BuscaRucSOAP, BuscaRuc.class, features);
    }

}
