package catalogo.consultpide.org.buscaruc.buscaruc;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-04-21T17:47:41.201-05:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://www.BuscaRuc.org/BuscaRuc/", name = "BuscaRuc")
@XmlSeeAlso({ ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BuscaRuc {

    @WebMethod(operationName = "BuscaRuc", action = "http://www.BuscaRuc.org/BuscaRuc/BuscaRuc")
    @WebResult(name = "BuscaRucResponse", targetNamespace = "http://www.BuscaRuc.org/BuscaRuc/", partName = "BuscaRucResponse")
    public BuscaRucResponse buscaRuc(

        @WebParam(partName = "BuscaRucRequest", name = "BuscaRucRequest", targetNamespace = "http://www.BuscaRuc.org/BuscaRuc/")
        java.lang.String buscaRucRequest
    );
}
