spring:
  application:
    name: persistence
  datasource:
    url: jdbc:postgresql://localhost:5432/ctdsys
    username: ctdsys_user
    password: CTDSYS
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
server:
  port: 9000